# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('odpiralni_tecaj', models.FloatField(verbose_name='Odpiralni tečaj')),
                ('uradni_tecaj', models.FloatField(verbose_name='Uradni tečaj')),
                ('volumen_trgovanja', models.IntegerField(verbose_name='Volumen trgovanja')),
                ('stevilo_delnic', models.IntegerField(verbose_name='Število vseh delnic')),
            ],
        ),
        migrations.CreateModel(
            name='Dividenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('vrednost', models.FloatField(verbose_name='Vrednost')),
            ],
        ),
        migrations.CreateModel(
            name='Podjetje',
            fields=[
                ('simbol', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Simbol')),
                ('polno_ime', models.TextField(verbose_name='Polno ime')),
                ('lokacija', models.TextField(verbose_name='Lokacija')),
                ('panoga', models.TextField(verbose_name='Panoga')),
                ('ipo', models.DateField(verbose_name='IPO')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('vrednost', models.FloatField(verbose_name='Vrednost')),
                ('kolicina', models.IntegerField(verbose_name='Količina')),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol')),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoslovniPodatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leto', models.IntegerField(verbose_name='Leto')),
                ('cetrtletje', models.IntegerField(verbose_name='Četrtletje')),
                ('promet', models.FloatField(verbose_name='Promet')),
                ('dobicek', models.FloatField(verbose_name='Dobicek')),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol')),
            ],
        ),
        migrations.AddField(
            model_name='dividenda',
            name='simbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol'),
        ),
        migrations.AddField(
            model_name='delnica',
            name='simbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol'),
        ),
    ]
