# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('odpiralniTecaj', models.FloatField(verbose_name='Odpiralni tečaj')),
                ('zapiralniTecaj', models.FloatField(verbose_name='Zapiralni tečaj')),
                ('nepopravljenZapiralniTecaj', models.FloatField(verbose_name='Nepopravjen zapiralni tečaj')),
                ('volumenTrgovanja', models.BigIntegerField(verbose_name='Volumen trgovanja')),
                ('steviloDelnic', models.BigIntegerField(verbose_name='Število vseh delnic')),
            ],
        ),
        migrations.CreateModel(
            name='Dividenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('vrednost', models.FloatField(verbose_name='Vrednost')),
            ],
        ),
        migrations.CreateModel(
            name='Podjetje',
            fields=[
                ('simbol', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Simbol')),
                ('polnoIme', models.TextField(verbose_name='Polno ime')),
                ('lokacija', models.TextField(verbose_name='Lokacija')),
                ('sektor', models.TextField(verbose_name='Sektor')),
                ('industrija', models.TextField(verbose_name='Industrija')),
                ('ipo', models.TextField(verbose_name='IPO')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('vrednost', models.FloatField(verbose_name='Vrednost')),
                ('kolicina', models.BigIntegerField(verbose_name='Količina')),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol')),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
        ),
        migrations.CreateModel(
            name='PoslovniPodatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leto', models.IntegerField(verbose_name='Leto')),
                ('cetrtletje', models.IntegerField(verbose_name='Četrtletje')),
                ('promet', models.FloatField(verbose_name='Promet')),
                ('dobicek', models.FloatField(verbose_name='Dobicek')),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol')),
            ],
        ),
        migrations.AddField(
            model_name='dividenda',
            name='simbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol'),
        ),
        migrations.AddField(
            model_name='delnica',
            name='simbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelniceWebApp.Podjetje', verbose_name='Simbol'),
        ),
    ]
