# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelniceWebApp', '0003_auto_20170514_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delnica',
            old_name='odpiralni_tecaj',
            new_name='odpiralniTecaj',
        ),
        migrations.RenameField(
            model_name='delnica',
            old_name='stevilo_delnic',
            new_name='steviloDelnic',
        ),
        migrations.RenameField(
            model_name='delnica',
            old_name='volumen_trgovanja',
            new_name='volumenTrgovanja',
        ),
        migrations.RemoveField(
            model_name='delnica',
            name='uradni_tecaj',
        ),
        migrations.AddField(
            model_name='delnica',
            name='nepopravljenZapiralniTecaj',
            field=models.FloatField(default=0, verbose_name='Nepopravjen zapiralni tečaj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delnica',
            name='zapiralniTecaj',
            field=models.FloatField(default=0, verbose_name='Zapiralni tečaj'),
            preserve_default=False,
        ),
    ]
